udev: Allow wayland on hybrid vendor nvidia machines
endlessm/gdm pull request #88
Opened 2023-12-05 11:21 UTC by starnight

We currently disable wayland on machines with the vendor nvidia driver upstream if hybrid graphics are in place because there is poor performance for multimonitor use cases.

But springing that change on users in F37 this late in the game isn't nice, so instead default to Xorg and provide wayland as an option in the menu.

https://bugzilla.redhat.com/show_bug.cgi?id=2128910

Have this patch from Fedora gdm.

Source: https://src.fedoraproject.org/rpms/gdm/c/27625e5ff87b21ad983d2bb53541361a7201755a

https://phabricator.endlessm.com/T35012

2023-12-05 12:25 UTC, dsd commented
This is not the configuration shipped by Fedora.
It currently defaults to wayland on this setup.
Probably via this change:
https://src.fedoraproject.org/rpms/gdm/blob/rawhide/f/0001-udev-Stick-with-wayland-on-hybrid-nvidia-with-vendor.patch

2023-12-05 12:27 UTC, dsd requested changes
please update to use Fedora's current setup

2023-12-06 04:24 UTC, starnight commented
> This is not the configuration shipped by Fedora. It currently defaults to wayland on this setup. Probably via this change: https://src.fedoraproject.org/rpms/gdm/blob/rawhide/f/0001-udev-Stick-with-wayland-on-hybrid-nvidia-with-vendor.patch

This patch from Fedora rawhide is based on gdm 45.  But, current EOS master is gdm 43.  So, there are some conflict.  And, that's why I choose the origin [patch](https://src.fedoraproject.org/rpms/gdm/c/27625e5ff87b21ad983d2bb53541361a7201755a).

2023-12-06 04:28 UTC, starnight commented
Well, I think using Wayland directly is okay with the NVIDIA driver.
 
Pushed a new commit backported from https://src.fedoraproject.org/rpms/gdm/blob/rawhide/f/0001-udev-Stick-with-wayland-on-hybrid-nvidia-with-vendor.patch

2023-12-06 09:39 UTC, merged